{% set version = "1.0.9" %}
{% set commit = "317247960efa47d389cfbdae8ae659252f06731d" %}

package:
  name: pyspharm
  version: {{ version }}

source:
  url: https://github.com/jswhit/pyspharm/archive/{{ commit }}.tar.gz
  sha256: e579c8d72f09a3f9c6c797f67097f028793b3d37eb84dcca17f1a2655da76f3a

build:
  number: 1014
  skip: True  # [win]
  skip: True  # [py>=312]
  script: "{{ PYTHON }} -m pip install --no-deps -vv ."

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}  # [win]
  host:
    - python
    - pip
    - numpy
    - meson-python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - spharm

about:
  home: https://github.com/jswhit/pyspharm
  license: LicenseRef-spherepack
  license_file: LICENSE.spherepack
  summary: 'Provides an object-oriented python interface to the NCAR SPHEREPACK library'

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
