{% set version = "1.0.9" %}
{% set commit = "e1e9cfef0c9144bad0f480e07926f454bca85a8a" %}

package:
  name: pyspharm
  version: {{ version }}

source:
  url: https://github.com/jswhit/pyspharm/archive/{{ commit }}.tar.gz
  sha256: 06baee3b5ce9c6bd262da624dedf4769e9e67583ca655960d50abbc7969add81

build:
  number: 1012
  skip: True  # [win and py3k or win64 or py>=312]

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}  # [win]
  host:
    - python
    - numpy
  run:
    - python

test:
  imports:
    - spharm

about:
  home: https://github.com/jswhit/pyspharm
  license: spherepack
  license_file: LICENSE.spherepack
  summary: 'Provides an object-oriented python interface to the NCAR SPHEREPACK library'

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
