{% set version = "1.0.9" %}
{% set commit = "b913aac7a25495caaa253ab4570f50a398e5639c" %}

package:
  name: pyspharm
  version: {{ version }}

source:
  url: https://github.com/jswhit/pyspharm/archive/{{ commit }}.tar.gz
  sha256: 726e8884aa598c4e3ee959cd3ca64d4748818ff277b41d48523cd6d70882ceb9

build:
  number: 1007
  skip: True  # [win and py3k or win64]

requirements:
  build:
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - spharm

about:
  home: https://github.com/jswhit/pyspharm
  license: spherepack
  license_file: LICENSE.spherepack
  summary: 'Provides an object-oriented python interface to the NCAR SPHEREPACK library'

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
