travis:
  secure:
    BINSTAR_TOKEN: fZYDhohHFPk+k0FIcKJbuVQR6X8FZk1x3+n+gXIKaHlM5W1rVRF6GXnS45YkGzcpa/spZHfMjWgG1A2v03ngp06ro3ZXaGvUtdXLwLMH60xvo0aPEA3u8le5Jb2bT00XFNrA34fW9mXL3s72CfA4PRvlgwzqsZjG8aV/YtMsP8GyLkfupcDlCGkT5BMLsCN99w5PxDI4G5qchy9WZk198I9mOb6SJYf/0jWR+rdx010YyVGlYdYK8GNfvH8F2byKAZA5tJeZUn4fPoh2bqVXmYPX5fEUP2H8wOpkEh9D1gD5+4Yjzjp6uJRYouNf1kXMwI+ntv3vZoafE1ewQMc3TmwkTNNE58jNehD8FntoG3JqgFV7oY5Accf4DTbmDBxtW1ZzuIC82JNL5X7l9wgEZOkFBR9uTtLdepu+V6v4Od77h7bqwtzc0YfmnOEu+9sUfCcqxyO9kf1nBgxHaljT1pLVSE1Byahnll92ongBS4ll6dh9TlRYRfjRHh6yb0a0zfLo1ZjO9pz6y0n67LoP1E4yRUKnHc/nfDo/sASJVG6CRHYlXX8XCJiIMnrg2ik/Dmav8wtM8eqdShOacREeTxyzk/tzrHgsBO7yGdyXa/sCjSPR462F2QMadML8scee4EWROHG0dnUb6qZGMAD551DenMHDM6J6X+Z49gLmqz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
